#!/usr/bin/env bash
set -Eeuo pipefail

: "${USERNAME:?USERNAME is required}"

export DEBIAN_FRONTEND=noninteractive
apt-get -o Acquire::Retries=5 update
apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
    gosu \
    openssh-server

install -d -m 0755 /run/sshd /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/90-agile-sonic.conf <<EOF
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
PubkeyAuthentication yes
UsePAM yes
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
AllowUsers ${USERNAME}
EOF

# Validate the daemon configuration, then remove build-time host keys. Fresh,
# container-specific keys are generated by entrypoint.sh at runtime.
ssh-keygen -A
/usr/sbin/sshd -t
rm -f /etc/ssh/ssh_host_*_key /etc/ssh/ssh_host_*_key.pub

apt-get clean
rm -rf /var/lib/apt/lists/*
